### ISSUE TITLE
获取商品信息都是无序的嘛？

### ISSUE THREAD

**Issue by Mr-lins** [976431yang/YQInAppPurchaseTool#1]
大神 
//向苹果询问哪些商品能够购买
    [IAPTool requestProductsWithProductArray:@[@"org60",
                                               @"org300",
                                               @"org600",
                                               @"org1000"]];我传入数组是按照价格从小到大排好序了但是获取到商品之后是无序的。如果我要按商品价格从小到大实现要怎么做处理呢？希望指点下

**Comment by Mr-lins** [comment]
![72b85818-d5c5-43c6-945d-b4f5a7e7dd4b](https://user-images.githubusercontent.com/26573094/28807354-a3c6a76e-76a7-11e7-8924-1a39f2251111.png)
已经解决    我在代理方法上面加了个冒泡排序   获取到商品之后就有序了

**Comment by Mr-lins** [comment]
大神   还有个问题想请教下。你这个内购流程是内置模式验证并返回receipt信息的，我要服务器模式验证的话是不是把整个receipt信息发给自己的后台验证？

**Comment by 976431yang** [comment]
是的。其实我这个封装封装得挺简单的，内容并不多，看看源代码就能明白。

不好意思我上github上的不勤，现在才看到。
